#!/bin/bash
# Import Apache virtual hosts into VeloServe and optionally swap Apache for VeloServe.
#
# VeloServe replaces Apache on port 80 (and 443 with SSL) serving all cPanel accounts.
# Reads the existing Apache httpd.conf and converts VirtualHosts (including per-domain
# SSL certificates) to VeloServe config.
#
# Usage:
#   ./import-apache-and-swap.sh              # Generate config, show swap instructions
#   ./import-apache-and-swap.sh --swap       # Generate config + stop Apache + start VeloServe
#   ./import-apache-and-swap.sh --config-only # Only regenerate /etc/veloserve/veloserve.toml

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

VELOSERVE_CONFIG="/etc/veloserve/veloserve.toml"
VELOSERVE_BIN="/usr/local/bin/veloserve"

if [ -f "/usr/local/apache/conf/httpd.conf" ]; then
    HTTPD_CONF="/usr/local/apache/conf/httpd.conf"
elif [ -f "/etc/httpd/conf/httpd.conf" ]; then
    HTTPD_CONF="/etc/httpd/conf/httpd.conf"
elif [ -f "/etc/apache2/apache2.conf" ]; then
    HTTPD_CONF="/etc/apache2/apache2.conf"
else
    echo -e "${RED}Error: Could not find Apache httpd.conf${NC}"
    echo "Looked in: /usr/local/apache/conf/ /etc/httpd/conf/ /etc/apache2/"
    exit 1
fi

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Run as root${NC}"
    exit 1
fi

if [ ! -x "$VELOSERVE_BIN" ]; then
    echo -e "${RED}Error: VeloServe not found at $VELOSERVE_BIN${NC}"
    echo "Install first: ./install-whm-plugin.sh"
    exit 1
fi

DO_SWAP=false
CONFIG_ONLY=false
for arg in "$@"; do
    case "$arg" in
        --swap)        DO_SWAP=true ;;
        --config-only) CONFIG_ONLY=true ;;
        -h|--help)
            echo "Usage: $0 [--swap] [--config-only]"
            echo "  --swap        Stop Apache, start VeloServe on port 80/443"
            echo "  --config-only Only regenerate $VELOSERVE_CONFIG"
            exit 0
            ;;
    esac
done

echo -e "${GREEN}VeloServe: Import Apache virtual hosts${NC}"
echo "========================================"
echo "Apache config: $HTTPD_CONF"
echo ""

if [ -f "$VELOSERVE_CONFIG" ]; then
    cp -a "$VELOSERVE_CONFIG" "${VELOSERVE_CONFIG}.bak.$(date +%Y%m%d%H%M%S)"
    echo -e "${GREEN}Backed up existing config${NC}"
fi

mkdir -p /etc/veloserve /var/log/veloserve /var/cache/veloserve /run/veloserve

# Detect best available EA-PHP
EA_PHP_CGI=""
for ver in 84 83 82 81 80 74; do
    if [ -x "/opt/cpanel/ea-php${ver}/root/usr/bin/php-cgi" ]; then
        EA_PHP_CGI="/opt/cpanel/ea-php${ver}/root/usr/bin/php-cgi"
        echo -e "${GREEN}EA-PHP detected: $EA_PHP_CGI${NC}"
        break
    fi
done
[ -z "$EA_PHP_CGI" ] && EA_PHP_CGI="/usr/bin/php-cgi"
[ ! -x "$EA_PHP_CGI" ] && EA_PHP_CGI="/usr/bin/php"

# Detect cPanel default SSL cert
CPANEL_CERT="/var/cpanel/ssl/cpanel/cpanel.pem"
SSL_BLOCK=""
if [ -f "$CPANEL_CERT" ]; then
    SSL_BLOCK="[ssl]
cert = \"$CPANEL_CERT\"
key = \"$CPANEL_CERT\"
"
    echo -e "${GREEN}Default SSL cert: $CPANEL_CERT${NC}"
fi

cat > "$VELOSERVE_CONFIG" << BASEEOF
# VeloServe Configuration
# Generated by import-apache-and-swap.sh
# Replaces Apache for all cPanel accounts on port 80 and 443.
# Per-account SSL certs are imported from Apache SSLCertificateFile/Key.

[server]
listen = "0.0.0.0:80"
listen_ssl = "0.0.0.0:443"
workers = "auto"
max_connections = 10000

[php]
enable = true
mode = "cgi"
version = "8.3"
binary_path = "$EA_PHP_CGI"
workers = 16
memory_limit = "512M"
max_execution_time = 60
error_log = "/var/log/veloserve/php-error.log"

ini_settings = [
    "opcache.enable=1",
    "opcache.memory_consumption=256",
    "opcache.max_accelerated_files=20000",
    "opcache.revalidate_freq=2",
]

$SSL_BLOCK
[cache]
enable = true
storage = "memory"
memory_limit = "1G"
default_ttl = 3600
disk_path = "/var/cache/veloserve"

# === Virtual hosts imported from Apache ===
BASEEOF

echo "Converting Apache virtual hosts..."
if "$VELOSERVE_BIN" config convert-apache --input "$HTTPD_CONF" --output /tmp/_vs_vhosts.toml --vhosts-only 2>/dev/null; then
    if [ -s /tmp/_vs_vhosts.toml ]; then
        cat /tmp/_vs_vhosts.toml >> "$VELOSERVE_CONFIG"
        VHOST_COUNT=$(grep -c '^\[\[virtualhost\]\]' "$VELOSERVE_CONFIG" || true)
        echo -e "${GREEN}Imported $VHOST_COUNT virtual host(s) (with SSL where present)${NC}"
    fi
    rm -f /tmp/_vs_vhosts.toml
else
    echo -e "${YELLOW}Warning: convert-apache returned no vhosts. Add [[virtualhost]] blocks manually.${NC}"
fi

"$VELOSERVE_BIN" config validate --config "$VELOSERVE_CONFIG" 2>/dev/null || true

echo ""
echo "Config written to: $VELOSERVE_CONFIG"

if [ "$CONFIG_ONLY" = true ]; then
    echo -e "${GREEN}Done (config-only). Run '$0 --swap' to activate.${NC}"
    exit 0
fi

if [ "$DO_SWAP" = true ]; then
    echo ""
    echo -e "${YELLOW}Swapping: stopping Apache, starting VeloServe on 80/443 ...${NC}"
    systemctl stop httpd 2>/dev/null || systemctl stop apache2 2>/dev/null || service httpd stop 2>/dev/null || true
    systemctl disable httpd 2>/dev/null || systemctl disable apache2 2>/dev/null || true
    systemctl restart veloserve
    systemctl enable veloserve 2>/dev/null || true
    sleep 2
    if systemctl is-active --quiet veloserve; then
        echo -e "${GREEN}VeloServe is now serving all accounts on port 80 and 443.${NC}"
    else
        echo -e "${RED}VeloServe failed to start! Reverting to Apache...${NC}"
        systemctl start httpd 2>/dev/null || systemctl start apache2 2>/dev/null || true
        echo "Check logs: journalctl -u veloserve"
        exit 1
    fi
    echo ""
    echo "To revert:  systemctl stop veloserve && systemctl start httpd"
    exit 0
fi

echo ""
echo "To swap Apache for VeloServe:"
echo "  $0 --swap"
echo ""
echo "Or manually:"
echo "  systemctl stop httpd"
echo "  systemctl start veloserve"
echo "  systemctl disable httpd && systemctl enable veloserve"
